c33s_core:
    bundles:
        #######################################################################
        # symfony
        #######################################################################
        assetic:
            class: false
        doctrine:
            class: false
        swiftmailer:
            class: false
        #######################################################################
        # extra
        #######################################################################
        cocur_human_date:
            class: Cocur\HumanDate\Bridge\Symfony\CocurHumanDateBundle
        c33s_static_page_content:
            class: c33s\StaticPageContentBundle\c33sStaticPageContentBundle
        c33s_attachment:
            class: c33s\AttachmentBundle\c33sAttachmentBundle
        c33s_menu:
            class: c33s\MenuBundle\c33sMenuBundle
        bazinga_propel_event_dispatcher:
            class: Bazinga\Bundle\PropelEventDispatcherBundle\BazingaPropelEventDispatcherBundle
        propel:
            class: Propel\PropelBundle\PropelBundle
        liip_imagine:
            class: Liip\ImagineBundle\LiipImagineBundle
        liip_monitor:
            class: Liip\MonitorBundle\LiipMonitorBundle
        mobile_detect:
            class: SunCat\MobileDetectBundle\MobileDetectBundle
        zenstruck_slugify:
            class: Zenstruck\SlugifyBundle\ZenstruckSlugifyBundle
        admingenerator_generator:
            class: Admingenerator\GeneratorBundle\AdmingeneratorGeneratorBundle
        fkr_css_url_rewrite:
            class: Fkr\CssURLRewriteBundle\FkrCssURLRewriteBundle
        fos_user:
            class: FOS\UserBundle\FOSUserBundle
        knp_gaufrette:
            class: Knp\Bundle\GaufretteBundle\KnpGaufretteBundle
        knp_markdown:
            class: Knp\Bundle\MarkdownBundle\KnpMarkdownBundle
        avocode_form_extensions:
            class: Avocode\FormExtensionsBundle\AvocodeFormExtensionsBundle
        white_october_pagerfanta:
            class: WhiteOctober\PagerfantaBundle\WhiteOctoberPagerfantaBundle
        somya_asset_management:
            class: Smoya\Bundle\AssetManagementBundle\SmoyaAssetManagementBundle
        #liip_hyphenator:
        #    class: Liip\HyphenatorBundle\LiipHyphenatorBundle
        #knp_menu:
        #    class: Knp\Bundle\MenuBundle\KnpMenuBundle
        #c33s_crazy_egg:
        #   class: c33s\Bundle\CrazyEggBundle
    twig:
        app:
            debug:      false
            use_cdn:    false
            name:       "long name"
            name_short: "short name"
            hinclude:   true
        google:
            tracking:
                id:      %ga_tracking_id%
                enabled: %ga_tracking_enabled%
                multi_domain: true
                domain: %master_domain%
                enable_GDN_impression_reporting: true
            webmaster_tools:
        page:
            title: ""
            author: ""
            keywords:
                - my keyword
            description: |
                my description
        contact:
            company:   
            street:    
            mobile: 
            phone:     
            fax:       
            mail:      
            www:       http://
            zip:       
            city:      
            country:   
            title:     
            firstname: 
            lastname:  
            map:
#                lat: 0.0
#                long: 0.0
#                marker: 
#                    image: http://%master_domain%/media/cache/logotop/media/images/logo.png
#                    size: [32,32]
#                    shadow:
#                        image: http://%master_domain%/media/cache/logotop/media/images/logo-alt.png
#                        size: [32,32]
#    datahandler:
#        levels: 3
#        db_maps: 
#            picture:
#                primary_string: Title
#                file_fields: [ attachment ]
#                directory: gallery
#                class: 'c33s\ModelBundle\Model\Picture'
#            service:
#                primary_string: Name
#                file_fields: [ picture ]
#                directory: service
#                class: 'c33s\ModelBundle\Model\Service'
#            information:
#                primary_string: Name
#                file_fields: [ imageSmall, imageLarge ]
#                directory: information
#                class: 'c33s\ModelBundle\Model\Information'
#            link:
#                primary_string: Name
#                file_fields: [ picture ]
#                directory: link
#                class: 'c33s\ModelBundle\Model\Link'
#            team:
#                primary_string: Lastname
#                file_fields: [ picture ]
#                directory: team
#                class: 'c33s\ModelBundle\Model\Team'
#            prepostgallery:
#                primary_string: Name
#                file_fields: [ picture, pictureBefore, pictureAfter ]
#                directory: pre-post-gallery
#                class: 'c33s\ModelBundle\Model\PrePostGallery'
#        class_maps:
#            'c33s\ModelBundle\Model\Picture': picture
#            'c33s\ModelBundle\Model\Information': information
#            'c33s\ModelBundle\Model\Link': link
#            'c33s\ModelBundle\Model\Team': team
#            'c33s\ModelBundle\Model\Service': service
#            'c33s\ModelBundle\Model\PrePostGallery': prepostgallery