parameters:
#    c33s_core.example.class: c33s\CoreBundle\Example

services:
    c33s_core.inflector:
        class: c33s\CoreBundle\Util\AkelosInflector
    #twig extensions
    c33s_core.twig.config_variables_extension:
        class: c33s\CoreBundle\Twig\ConfigVariablesExtension
        arguments:
            - %c33s_core.config.twig_variables%
        tags:
            - { name: twig.extension }
    c33s_core.twig.quickfilter_extension:
        class: c33s\CoreBundle\Twig\QuickFilterExtension
        arguments:
            - @c33s_core.inflector
        tags:
            - { name: twig.extension }
    c33s_core.security_helper:
        class: c33s\CoreBundle\Service\SecurityHelper
        arguments:
            - @security.context
            - @event_dispatcher
            - @request
            - @router
        public: true    #for request injection
        scope: request  #for request injection
#       UPSF2.4 Prepeare for upgrade
#        calls:
#            - [setRequest, [@request_stack]]
# https://stackoverflow.com/questions/9332925/how-to-inject-the-request-into-a-service