parameters:
#    c33s_core.example.class: c33s\CoreBundle\Example

services:
#    c33s_core.example:
#        class: %c33s_core.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
