name: namespace/name
type: project
license: proprietary
authors:
  - name: noname

description: 'my description'
autoload:
    psr-0: { '': src/ }
repositories:
  - type: vcs
    url: https://github.com/c33s/AssetManagementBundle.git
require:
    symfony/framework-standard-edition: '2.3.*'
    c33s/core-bundle:   'dev-master'
    #### Locks from corebundle ###########################################################################
    #cedriclombardot/admingenerator-generator-bundle: '2.3.*@dev'
    cedriclombardot/admingenerator-generator-bundle: 'dev-master#6dd565dacb6e668b9bcfa216a2acca356949375c'
    avocode/form-extensions-bundle:                  'dev-master#cd83e011f7fcc979cb5714c33423845c7ce36f0a'
    #white-october/pagerfanta-bundle: '1.0.*@dev'
    white-october/pagerfanta-bundle:                 'dev-master#606467f9e9f9e80975128db589eec2f9d11139c2'
    #### End Locks corebundle ###########################################################################

scripts:
    post-install-cmd:
      - 'Incenteev\ParameterHandler\ScriptHandler::buildParameters'
      - 'Sensio\Bundle\DistributionBundle\Composer\ScriptHandler::buildBootstrap'
      - 'Sensio\Bundle\DistributionBundle\Composer\ScriptHandler::clearCache'
      - 'Sensio\Bundle\DistributionBundle\Composer\ScriptHandler::installAssets'
      - 'Sensio\Bundle\DistributionBundle\Composer\ScriptHandler::installRequirementsFile'
    post-update-cmd:
      - 'Incenteev\ParameterHandler\ScriptHandler::buildParameters'
      - 'Sensio\Bundle\DistributionBundle\Composer\ScriptHandler::buildBootstrap'
      - 'Sensio\Bundle\DistributionBundle\Composer\ScriptHandler::clearCache'
      - 'Sensio\Bundle\DistributionBundle\Composer\ScriptHandler::installAssets'
      - 'Sensio\Bundle\DistributionBundle\Composer\ScriptHandler::installRequirementsFile'
config:
    bin-dir: bin
    component-dir: "web/components"
    component-baseurl: "/components"
minimum-stability: stable
extra:
    symfony-app-dir: app
    symfony-web-dir: web
    incenteev-parameters: { file: app/config/parameters.yml }
    branch-alias: { dev-master: 2.3-dev }
