name:           namespace/name
type:           project
license:        proprietary

authors:
  - name:       noname

description:    'my description'

autoload:
    psr-0: { '': src/ }

repositories:
  - type: composer
    url: http://satis.c33s.net

require:
    symfony/framework-standard-edition: '2.3.*'
    c33s/core-bundle:                   'dev-master'
    
scripts:
    post-install-cmd:
      - 'Incenteev\ParameterHandler\ScriptHandler::buildParameters'
      - 'Sensio\Bundle\DistributionBundle\Composer\ScriptHandler::buildBootstrap'
      - 'Sensio\Bundle\DistributionBundle\Composer\ScriptHandler::clearCache'
      - 'Sensio\Bundle\DistributionBundle\Composer\ScriptHandler::installAssets'
      - 'Sensio\Bundle\DistributionBundle\Composer\ScriptHandler::installRequirementsFile'
    post-update-cmd:
      - 'Incenteev\ParameterHandler\ScriptHandler::buildParameters'
      - 'Sensio\Bundle\DistributionBundle\Composer\ScriptHandler::buildBootstrap'
      - 'Sensio\Bundle\DistributionBundle\Composer\ScriptHandler::clearCache'
      - 'Sensio\Bundle\DistributionBundle\Composer\ScriptHandler::installAssets'
      - 'Sensio\Bundle\DistributionBundle\Composer\ScriptHandler::installRequirementsFile'

config:
    bin-dir:            bin
    component-dir:      "web/media/components"
    component-baseurl:  "/media/components"

minimum-stability:  stable

extra:
    symfony-app-dir:        app
    symfony-web-dir:        web
    incenteev-parameters:   { file: app/config/parameters.yml }
    branch-alias:           { dev-master: 2.3-dev }
