# Assetic Configuration
assetic:
    debug:          '%kernel.debug%'
    write_to:       '%kernel.root_dir%/../web/'
    use_controller: false
    bundles:        [ 'C33sCoreBundle', 'AppBundle' ]
    #java:           /usr/bin/java
    node:           '%node.bin%'
    filters:
        uglifyjs2:
            bin:    '%kernel.root_dir%/../node_modules/uglify-js/bin/uglifyjs'
        uglifycss:
            bin:    '%kernel.root_dir%/../node_modules/uglifycss/uglifycss'
        cssrewrite: ~
        lessphp:
            paths:
                - '%kernel.root_dir%/../src/AppBundle/Resources/private/less/'
                - '%kernel.root_dir%/../src/'
                - '%kernel.root_dir%/../vendor/'
                - '%kernel.root_dir%/../'
            apply_to: '\.less$'
        
        #closure:
        #    jar: %kernel.root_dir%/Resources/java/compiler.jar
        #yui_css:
        #    jar: %kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar
        #yui_js:
        #    jar: %kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar

#    assets:
#      bootstrap3_js:
#        combine: true
#        output: 'media/generated/js/_bootstrap3.js'
#        inputs:
#            - '%kernel.root_dir%/../vendor/twbs/bootstrap/js/affix.js'
#            - '%kernel.root_dir%/../vendor/twbs/bootstrap/js/alert.js'
#            - '%kernel.root_dir%/../vendor/twbs/bootstrap/js/button.js'
#            - '%kernel.root_dir%/../vendor/twbs/bootstrap/js/carousel.js'
#            - '%kernel.root_dir%/../vendor/twbs/bootstrap/js/collapse.js'
#            - '%kernel.root_dir%/../vendor/twbs/bootstrap/js/dropdown.js'
#            - '%kernel.root_dir%/../vendor/twbs/bootstrap/js/modal.js'
#            - '%kernel.root_dir%/../vendor/twbs/bootstrap/js/tooltip.js'
#            - '%kernel.root_dir%/../vendor/twbs/bootstrap/js/popover.js'
#            - '%kernel.root_dir%/../vendor/twbs/bootstrap/js/scrollspy.js'
#            - '%kernel.root_dir%/../vendor/twbs/bootstrap/js/tab.js'
#            - '%kernel.root_dir%/../vendor/twbs/bootstrap/js/transition.js'
        #filters: [?yui_js]

# no bootstrap_css needed, is loaded with single file @import in corebundle
#      bootstrap3_css:
#        output: 'media/generated/css/bootstrap3.css'
#        inputs:
#            - '%kernel.root_dir%/../vendor/twbs/bootstrap/less/bootstrap.less'
#        filters: [lessphp,cssembed]
