c33s_contact_form:
    #email:
        #subject: [New contact inquiry]
        # Email address to use as "From:" in notification emails
        #sender_email:   your.email@example.com

        # These email addresses will receive notifications whenever someone submitted a contact form
        #recipients:
        #    - notification.email1@example.com
        #    - notification.email2@example.com

        # Set to true to also send the notification to the user filling the contact form
        # Beware that this opens the possibility to use the contact form as a spam relay!
        #send_copy_to_user:  false
    database: ~
