admingenerator_generator:
    # choose  and enable at least one
    use_propel:           true
    use_doctrine_orm:     false
    use_doctrine_odm:     false
    #dashboard_welcome_path:     MyDashboard_path
    # choose and uncomment only one
    base_admin_template: C33sCoreBundle::admin-base.html.twig
    #base_admin_template: AdmingeneratorGeneratorBundle::base_admin.html.twig
    # base_admin_template: AdmingeneratorGeneratorBundle::base_admin_assetic_less.html.twig

parameters:
    admingenerator.fieldguesser.propel.class:   'C33s\CoreBundle\Admingenerator\Guesser\PropelORMFieldGuesser'
    