# Assetic Configuration
assetic:
    debug:          %kernel.debug%
    use_controller: false
    bundles:        [ 'c33sCoreBundle' ]
    #java: /usr/bin/java
    filters:
        cssrewrite: ~
        lessphp:
          paths:
            ## old
            #- '%kernel.root_dir%/../vendor/twitter/bootstrap/less/'
            #- '%kernel.root_dir%/../vendor/fortawesome/font-awesome/less/'
            #- '@c33sCoreBundle/Resources/non-public/less/'
            #- '%kernel.root_dir%/../vendor/c33s/core-bundle/c33s/CoreBundle/Resources/non-public/less/'

            # @bundle notation does not work here
            ##- '@c33sCoreBundle/Resources/non-public/less/'
            - '%kernel.root_dir%/../vendor/twitter/bootstrap/less/'
            #bootstrap/less/
            - '%kernel.root_dir%/../vendor/twbs/'
            - '%kernel.root_dir%/../vendor/fortawesome/font-awesome/less/'
            - '%kernel.root_dir%/../src/DrBau/AdminBundle/Resources/non-public/less/'
            - '%kernel.root_dir%/../src/DrBau/WebpageBundle/Resources/non-public/less/'
            - '%kernel.root_dir%/../vendor/c33s/core-bundle/c33s/CoreBundle/Resources/non-public/less/'
          apply_to: "\.less$"
        #closure:
        #    jar: %kernel.root_dir%/Resources/java/compiler.jar
        #yui_css:
        #    jar: %kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar
        #yui_js:
        #    jar: %kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar
    assets:
      bootstrap_js:
        #combine: true
        output: 'generated/js/bootstrap.js'
        inputs:
            - '%kernel.root_dir%/../vendor/twitter/bootstrap/js/bootstrap-transition.js'
            - '%kernel.root_dir%/../vendor/twitter/bootstrap/js/bootstrap-alert.js'
            - '%kernel.root_dir%/../vendor/twitter/bootstrap/js/bootstrap-modal.js'
            - '%kernel.root_dir%/../vendor/twitter/bootstrap/js/bootstrap-dropdown.js'
            - '%kernel.root_dir%/../vendor/twitter/bootstrap/js/bootstrap-scrollspy.js'
            - '%kernel.root_dir%/../vendor/twitter/bootstrap/js/bootstrap-tab.js'
            - '%kernel.root_dir%/../vendor/twitter/bootstrap/js/bootstrap-tooltip.js'
            - '%kernel.root_dir%/../vendor/twitter/bootstrap/js/bootstrap-popover.js'
            - '%kernel.root_dir%/../vendor/twitter/bootstrap/js/bootstrap-button.js'
            - '%kernel.root_dir%/../vendor/twitter/bootstrap/js/bootstrap-collapse.js'
            - '%kernel.root_dir%/../vendor/twitter/bootstrap/js/bootstrap-carousel.js'
            - '%kernel.root_dir%/../vendor/twitter/bootstrap/js/bootstrap-typeahead.js'
            - '%kernel.root_dir%/../vendor/twitter/bootstrap/js/bootstrap-affix.js'
      bootstrap3_js:
        #combine: true
        output: 'generated/js/bootstrap3.js'
        inputs:
            - '%kernel.root_dir%/../vendor/twbs/bootstrap/js/affix.js'
            - '%kernel.root_dir%/../vendor/twbs/bootstrap/js/alert.js'
            - '%kernel.root_dir%/../vendor/twbs/bootstrap/js/button.js'
            - '%kernel.root_dir%/../vendor/twbs/bootstrap/js/carousel.js'
            - '%kernel.root_dir%/../vendor/twbs/bootstrap/js/collapse.js'
            - '%kernel.root_dir%/../vendor/twbs/bootstrap/js/dropdown.js'
            - '%kernel.root_dir%/../vendor/twbs/bootstrap/js/modal.js'
            - '%kernel.root_dir%/../vendor/twbs/bootstrap/js/tooltip.js'
            - '%kernel.root_dir%/../vendor/twbs/bootstrap/js/popover.js'
            - '%kernel.root_dir%/../vendor/twbs/bootstrap/js/scrollspy.js'
            - '%kernel.root_dir%/../vendor/twbs/bootstrap/js/tab.js'
            - '%kernel.root_dir%/../vendor/twbs/bootstrap/js/transition.js'
        #filters: [?yui_js]
# no responsive bootstrap needed in ember theme
      bootstrap_css_responsive:
        output: 'generated/css/bootstrap-responsive.css'
        inputs:
            - '%kernel.root_dir%/../vendor/twitter/bootstrap/less/responsive.less'
        filters: [lessphp,cssrewrite]  #cssembed

# no bootstrap_css needed, is loaded with single file @import in corebundle
#      bootstrap_css:
#        output: 'generated/css/bootstrap-responsive.css'
#        inputs:
#            - '%kernel.root_dir%/../vendor/twitter/bootstrap/less/bootstrap.less'
#        filters: [lessphp,cssembed]
