jms_translation:
    locales:    '%locales%'
    configs:
        app:
            dirs:               [ '%kernel.root_dir%', '%kernel.root_dir%/../src' ]
            output_dir:         '%kernel.root_dir%/Resources/translations'
            ignored_domains:    [ routes ]
            excluded_names:     [ '*TestCase.php', '*Test.php' ]
            excluded_dirs:      [ cache, data, logs ]
            #extractors:         [ alias_of_the_extractor ]
