knp_gaufrette:
    adapters:
        local_base:
            local:
                directory:  '%kernel.root_dir%/../web/media/storage/'

    filesystems:
        web_storage_fs:
            adapter:    local_base
