lexik_translation:
    fallback_locale:        "%locale%"          # (required) default locale to use
    managed_locales:        "%locales%"         # (required) locales that the bundle have to manage

    use_yml_tree:           true                # if "true" we will print a nice tree in the yml source files. It is a little slower.
    grid_input_type:        textarea            # define field type used in the grid (text|textarea)

    storage:
        type:                   propel          # where to store translations: "orm", "mongodb" or "propel"
        object_manager:         default         # The name of the entity / document manager which uses different connection (see: http://symfony.com/doc/current/cookbook/doctrine/multiple_entity_managers.html)
                                                # When using propel, this can be used to specify the propel connection name
    resources_registration:
        type:                   all             # resources type to register: "all", "files" or "database"
        managed_locales_only:   true            # will only load resources for managed locales
