liip_monitor:
    checks:
        #php_extensions: [apc, xdebug]
        symfony_version_check: ~
        #custom_error_pages_check: ~
        writable_directory: ['app/cache', 'web/upload']
        custom_error_pages:
          error_codes: [404, 500]
        http_service:
            host: "%master_domain%"
            port: 80
            status_code: 200
            #content: mycontent
        disc_usage: ~
        #security_advisory: ~
        #  percentage: 90
        #  path: /var/www

#DiscUsageCheck
#DoctrineDbalCheck
#HttpServiceCheck
#MemcacheCheck
#PhpExtensionsCheck
#ProcessActiveCheck
#SecurityAdvisoryCheck
#WritableDirectoryCheck
