propel:
    path:       "%kernel.root_dir%/../vendor/propel"
    phing_path: "%kernel.root_dir%/../vendor/phing"
#    logging:   %kernel.debug%
    build_properties:
        propel.mysql.tableType:                 InnoDB
        propel.namespace.autoPackage:           true
        propel.database: %propel_database_driver% #pgsql|mysql|sqlite|mssql|oracle
    behaviors:
        typehintable:                          vendor.willdurand.propel-typehintable-behavior.src.TypehintableBehavior
        publishable:                           vendor.willdurand.propel-publishable-behavior.src.PublishableBehavior
        c33s_attachable:                       vendor.c33s.attachment-bundle.c33s.AttachmentBundle.Behavior.C33sPropelBehaviorAttachable
        event_dispatcher:                      vendor.willdurand.propel-eventdispatcher-behavior.src.EventDispatcherBehavior

        #typehintable:                           vendor.willdurand.propel-typehintable-behavior.src.TypehintableBehavior
        #c33s_searchable:                        src.c33s.SearchIndexBundle.Behavior.C33sPropelBehaviorSearchable
        #extra_properties:                       path.to.ExtraPropertiesBehavior
    dbal:
#        driver:               %propel_database_driver_prefix%%propel_database_driver%
        driver:               %propel_database_driver%
        user:                 %propel_database_user%
        password:             %propel_database_password%
        dsn:                  %propel_database_dsn%
        options:              {}
        attributes:           {}
