# Swiftmailer Configuration
swiftmailer:
    transport:  "%mailer_transport%"
    host:       "%mailer_host%"
    username:   "%mailer_user%"
    password:   "%mailer_password%"
    spool:      { type: memory }
    transport:  "%mailer_transport%"
    username:   "%mailer_user%"
    password:   "%mailer_password%"
    host:       "%mailer_host%"
    port:       false
    encryption: "%mailer_encryption%"
    spool:
        type:       "%mailer_spool_type%"
#        path:               "%kernel.cache_dir%/swiftmailer/spool"


#    auth_mode:            ~
#    sender_address:       ~
#    antiflood:
#        threshold:            99
#        sleep:                0
#    delivery_address:     ~
#    disable_delivery:     ~
#    logging:              "%kernel.debug%"