knp_gaufrette:
    adapters:
        foo:
            local:
                directory: %kernel.root_dir%/..web/test/path
                create:     true
    filesystems:
        bar:
            adapter:    foo
            #alias:      foo_filesystem