imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: '@c33sCoreBundle/Resources/config/config.yml' }
    - { resource: config/admingenerator_generator.yml }
    - { resource: config/assetic.yml }
    - { resource: config/propel.yml }
    - { resource: config/fos_user.yml }
    - { resource: config/doctrine.yml }
    - { resource: config/gregwar_image.yml }
    - { resource: config/liip_imagine.yml }
    - { resource: config/swiftmailer.yml }
    - { resource: config/fkr_css_url_rewrite.yml }


framework:
    #esi:             ~
    translator:      { fallback: %locale% }
    secret:          %secret%
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trusted_proxies: ~
    session:         ~
    fragments:       ~

# Twig Configuration
twig:
    debug:            %kernel.debug%
    strict_variables: %kernel.debug%
    globals:
        app_name_short: 
        app_name: 
        app_name_long:  
        app_version:    
        app_phone:      
        app_fax:        
        app_email:      
        
        app_ga_tracking: "%ga_tracking%"
        app_description: ""
        app_author: ""
        app_keywords: []
        app_upload_dir: %upload_dir%
        app_use_cdn: false
        app_contact_company: 
        app_contact_street: 
        app_contact_mobile: 
        app_contact_phone: 
        app_contact_fax: 
        app_contact_mail: 
        app_contact_zip: 
        app_contact_city: 
        app_contact_country: 
        app_contact_title: 
        app_contact_firstname: 
        app_contact_lastname: 
